---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  slack:
    secure: UAW1lCTWdm0x/eDsdBFIO8BzB2q3hTEEzy1ShQvd/FQdhviEtdOjnpSsb5Gr+15ZC+C9vtM8x+CRTC+g0oHLrftkkHSIZsQq5QELbB1bK+vDhYBxwmoTmnnhV3o0N4scj+xp7/Jtn+8qH+ZNCaRrMMhCPBtBYMsvG6OIRhkRFmc=
